// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCompute creates a new instance of MockCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompute {
	mock := &MockCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompute is an autogenerated mock type for the Compute type
type MockCompute struct {
	mock.Mock
}

type MockCompute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompute) EXPECT() *MockCompute_Expecter {
	return &MockCompute_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockCompute
func (_mock *MockCompute) Parse(query string) (Query, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 Query
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Query, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Query); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(Query)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompute_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockCompute_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - query
func (_e *MockCompute_Expecter) Parse(query interface{}) *MockCompute_Parse_Call {
	return &MockCompute_Parse_Call{Call: _e.mock.On("Parse", query)}
}

func (_c *MockCompute_Parse_Call) Run(run func(query string)) *MockCompute_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCompute_Parse_Call) Return(query1 Query, err error) *MockCompute_Parse_Call {
	_c.Call.Return(query1, err)
	return _c
}

func (_c *MockCompute_Parse_Call) RunAndReturn(run func(query string) (Query, error)) *MockCompute_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockStorage
func (_mock *MockStorage) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockStorage_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockStorage_Expecter) Del(ctx interface{}, key interface{}) *MockStorage_Del_Call {
	return &MockStorage_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockStorage_Del_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Del_Call) Return(err error) *MockStorage_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorage_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockStorage_Expecter) Get(ctx interface{}, key interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(s string, err error) *MockStorage_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStorage
func (_mock *MockStorage) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *MockStorage_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockStorage_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(err error) *MockStorage_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}
