// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package slave

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSegmentsReader creates a new instance of MockSegmentsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegmentsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegmentsReader {
	mock := &MockSegmentsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSegmentsReader is an autogenerated mock type for the SegmentsReader type
type MockSegmentsReader struct {
	mock.Mock
}

type MockSegmentsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSegmentsReader) EXPECT() *MockSegmentsReader_Expecter {
	return &MockSegmentsReader_Expecter{mock: &_m.Mock}
}

// LastSegment provides a mock function for the type MockSegmentsReader
func (_mock *MockSegmentsReader) LastSegment() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastSegment")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSegmentsReader_LastSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastSegment'
type MockSegmentsReader_LastSegment_Call struct {
	*mock.Call
}

// LastSegment is a helper method to define mock.On call
func (_e *MockSegmentsReader_Expecter) LastSegment() *MockSegmentsReader_LastSegment_Call {
	return &MockSegmentsReader_LastSegment_Call{Call: _e.mock.On("LastSegment")}
}

func (_c *MockSegmentsReader_LastSegment_Call) Run(run func()) *MockSegmentsReader_LastSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSegmentsReader_LastSegment_Call) Return(s string, err error) *MockSegmentsReader_LastSegment_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSegmentsReader_LastSegment_Call) RunAndReturn(run func() (string, error)) *MockSegmentsReader_LastSegment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSegmentsWriter creates a new instance of MockSegmentsWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegmentsWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegmentsWriter {
	mock := &MockSegmentsWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSegmentsWriter is an autogenerated mock type for the SegmentsWriter type
type MockSegmentsWriter struct {
	mock.Mock
}

type MockSegmentsWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSegmentsWriter) EXPECT() *MockSegmentsWriter_Expecter {
	return &MockSegmentsWriter_Expecter{mock: &_m.Mock}
}

// WriteFullSegment provides a mock function for the type MockSegmentsWriter
func (_mock *MockSegmentsWriter) WriteFullSegment(segment string, data []byte) error {
	ret := _mock.Called(segment, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFullSegment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(segment, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSegmentsWriter_WriteFullSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFullSegment'
type MockSegmentsWriter_WriteFullSegment_Call struct {
	*mock.Call
}

// WriteFullSegment is a helper method to define mock.On call
//   - segment
//   - data
func (_e *MockSegmentsWriter_Expecter) WriteFullSegment(segment interface{}, data interface{}) *MockSegmentsWriter_WriteFullSegment_Call {
	return &MockSegmentsWriter_WriteFullSegment_Call{Call: _e.mock.On("WriteFullSegment", segment, data)}
}

func (_c *MockSegmentsWriter_WriteFullSegment_Call) Run(run func(segment string, data []byte)) *MockSegmentsWriter_WriteFullSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockSegmentsWriter_WriteFullSegment_Call) Return(err error) *MockSegmentsWriter_WriteFullSegment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSegmentsWriter_WriteFullSegment_Call) RunAndReturn(run func(segment string, data []byte) error) *MockSegmentsWriter_WriteFullSegment_Call {
	_c.Call.Return(run)
	return _c
}
