packages:
  kvdb/internal/database:
    interfaces:
      Storage:
      Compute:
  kvdb/internal/database/log/writer:
    interfaces:
      Segment:
  kvdb/internal/rpc/query:
    interfaces:
      Database:
  kvdb/internal/database/storage:
    interfaces:
      Engine:
      WAL:
  kvdb/internal/database/wal:
    interfaces:
      LogsWriter:
      LogsReader:
  kvdb/internal/database/replication/master:
    interfaces:
      TCPServer:
      SegmentsReader:
  kvdb/internal/database/replication/slave:
    interfaces:
      SegmentsReader:
      SegmentsWriter:
      Client:
