// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package master

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTCPServer creates a new instance of MockTCPServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTCPServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTCPServer {
	mock := &MockTCPServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTCPServer is an autogenerated mock type for the TCPServer type
type MockTCPServer struct {
	mock.Mock
}

type MockTCPServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTCPServer) EXPECT() *MockTCPServer_Expecter {
	return &MockTCPServer_Expecter{mock: &_m.Mock}
}

// ListenFunc provides a mock function for the type MockTCPServer
func (_mock *MockTCPServer) ListenFunc(ctx context.Context, f func(ctx context.Context, request []byte) []byte) {
	_mock.Called(ctx, f)
	return
}

// MockTCPServer_ListenFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenFunc'
type MockTCPServer_ListenFunc_Call struct {
	*mock.Call
}

// ListenFunc is a helper method to define mock.On call
//   - ctx
//   - f
func (_e *MockTCPServer_Expecter) ListenFunc(ctx interface{}, f interface{}) *MockTCPServer_ListenFunc_Call {
	return &MockTCPServer_ListenFunc_Call{Call: _e.mock.On("ListenFunc", ctx, f)}
}

func (_c *MockTCPServer_ListenFunc_Call) Run(run func(ctx context.Context, f func(ctx context.Context, request []byte) []byte)) *MockTCPServer_ListenFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(ctx context.Context, request []byte) []byte))
	})
	return _c
}

func (_c *MockTCPServer_ListenFunc_Call) Return() *MockTCPServer_ListenFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTCPServer_ListenFunc_Call) RunAndReturn(run func(ctx context.Context, f func(ctx context.Context, request []byte) []byte)) *MockTCPServer_ListenFunc_Call {
	_c.Run(run)
	return _c
}

// NewMockSegmentsReader creates a new instance of MockSegmentsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegmentsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegmentsReader {
	mock := &MockSegmentsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSegmentsReader is an autogenerated mock type for the SegmentsReader type
type MockSegmentsReader struct {
	mock.Mock
}

type MockSegmentsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSegmentsReader) EXPECT() *MockSegmentsReader_Expecter {
	return &MockSegmentsReader_Expecter{mock: &_m.Mock}
}

// ReadNextSegment provides a mock function for the type MockSegmentsReader
func (_mock *MockSegmentsReader) ReadNextSegment(previousSegment string) (string, []byte, error) {
	ret := _mock.Called(previousSegment)

	if len(ret) == 0 {
		panic("no return value specified for ReadNextSegment")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, []byte, error)); ok {
		return returnFunc(previousSegment)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(previousSegment)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) []byte); ok {
		r1 = returnFunc(previousSegment)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(previousSegment)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSegmentsReader_ReadNextSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadNextSegment'
type MockSegmentsReader_ReadNextSegment_Call struct {
	*mock.Call
}

// ReadNextSegment is a helper method to define mock.On call
//   - previousSegment
func (_e *MockSegmentsReader_Expecter) ReadNextSegment(previousSegment interface{}) *MockSegmentsReader_ReadNextSegment_Call {
	return &MockSegmentsReader_ReadNextSegment_Call{Call: _e.mock.On("ReadNextSegment", previousSegment)}
}

func (_c *MockSegmentsReader_ReadNextSegment_Call) Run(run func(previousSegment string)) *MockSegmentsReader_ReadNextSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSegmentsReader_ReadNextSegment_Call) Return(s string, bytes []byte, err error) *MockSegmentsReader_ReadNextSegment_Call {
	_c.Call.Return(s, bytes, err)
	return _c
}

func (_c *MockSegmentsReader_ReadNextSegment_Call) RunAndReturn(run func(previousSegment string) (string, []byte, error)) *MockSegmentsReader_ReadNextSegment_Call {
	_c.Call.Return(run)
	return _c
}
