// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wal

import (
	"kvdb/internal/database"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogsWriter creates a new instance of MockLogsWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogsWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogsWriter {
	mock := &MockLogsWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogsWriter is an autogenerated mock type for the LogsWriter type
type MockLogsWriter struct {
	mock.Mock
}

type MockLogsWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogsWriter) EXPECT() *MockLogsWriter_Expecter {
	return &MockLogsWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockLogsWriter
func (_mock *MockLogsWriter) Write(batch []database.WriteRequest) error {
	ret := _mock.Called(batch)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]database.WriteRequest) error); ok {
		r0 = returnFunc(batch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogsWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockLogsWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - batch
func (_e *MockLogsWriter_Expecter) Write(batch interface{}) *MockLogsWriter_Write_Call {
	return &MockLogsWriter_Write_Call{Call: _e.mock.On("Write", batch)}
}

func (_c *MockLogsWriter_Write_Call) Run(run func(batch []database.WriteRequest)) *MockLogsWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]database.WriteRequest))
	})
	return _c
}

func (_c *MockLogsWriter_Write_Call) Return(err error) *MockLogsWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogsWriter_Write_Call) RunAndReturn(run func(batch []database.WriteRequest) error) *MockLogsWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogsReader creates a new instance of MockLogsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogsReader {
	mock := &MockLogsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogsReader is an autogenerated mock type for the LogsReader type
type MockLogsReader struct {
	mock.Mock
}

type MockLogsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogsReader) EXPECT() *MockLogsReader_Expecter {
	return &MockLogsReader_Expecter{mock: &_m.Mock}
}

// ReadLogs provides a mock function for the type MockLogsReader
func (_mock *MockLogsReader) ReadLogs() ([]database.WALRecord, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadLogs")
	}

	var r0 []database.WALRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.WALRecord, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.WALRecord); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.WALRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLogsReader_ReadLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadLogs'
type MockLogsReader_ReadLogs_Call struct {
	*mock.Call
}

// ReadLogs is a helper method to define mock.On call
func (_e *MockLogsReader_Expecter) ReadLogs() *MockLogsReader_ReadLogs_Call {
	return &MockLogsReader_ReadLogs_Call{Call: _e.mock.On("ReadLogs")}
}

func (_c *MockLogsReader_ReadLogs_Call) Run(run func()) *MockLogsReader_ReadLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogsReader_ReadLogs_Call) Return(wALRecords []database.WALRecord, err error) *MockLogsReader_ReadLogs_Call {
	_c.Call.Return(wALRecords, err)
	return _c
}

func (_c *MockLogsReader_ReadLogs_Call) RunAndReturn(run func() ([]database.WALRecord, error)) *MockLogsReader_ReadLogs_Call {
	_c.Call.Return(run)
	return _c
}
