// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// RunCommand provides a mock function for the type MockDatabase
func (_mock *MockDatabase) RunCommand(ctx context.Context, rawQuery string) (string, error) {
	ret := _mock.Called(ctx, rawQuery)

	if len(ret) == 0 {
		panic("no return value specified for RunCommand")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, rawQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, rawQuery)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_RunCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunCommand'
type MockDatabase_RunCommand_Call struct {
	*mock.Call
}

// RunCommand is a helper method to define mock.On call
//   - ctx
//   - rawQuery
func (_e *MockDatabase_Expecter) RunCommand(ctx interface{}, rawQuery interface{}) *MockDatabase_RunCommand_Call {
	return &MockDatabase_RunCommand_Call{Call: _e.mock.On("RunCommand", ctx, rawQuery)}
}

func (_c *MockDatabase_RunCommand_Call) Run(run func(ctx context.Context, rawQuery string)) *MockDatabase_RunCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_RunCommand_Call) Return(s string, err error) *MockDatabase_RunCommand_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDatabase_RunCommand_Call) RunAndReturn(run func(ctx context.Context, rawQuery string) (string, error)) *MockDatabase_RunCommand_Call {
	_c.Call.Return(run)
	return _c
}
