// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package writer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSegment creates a new instance of MockSegment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegment {
	mock := &MockSegment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSegment is an autogenerated mock type for the Segment type
type MockSegment struct {
	mock.Mock
}

type MockSegment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSegment) EXPECT() *MockSegment_Expecter {
	return &MockSegment_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockSegment
func (_mock *MockSegment) Write(bytes []byte) error {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSegment_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockSegment_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - bytes
func (_e *MockSegment_Expecter) Write(bytes interface{}) *MockSegment_Write_Call {
	return &MockSegment_Write_Call{Call: _e.mock.On("Write", bytes)}
}

func (_c *MockSegment_Write_Call) Run(run func(bytes []byte)) *MockSegment_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockSegment_Write_Call) Return(err error) *MockSegment_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSegment_Write_Call) RunAndReturn(run func(bytes []byte) error) *MockSegment_Write_Call {
	_c.Call.Return(run)
	return _c
}
