// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"kvdb/internal/conc"
	"kvdb/internal/database"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockEngine
func (_mock *MockEngine) Del(ctx context.Context, key string) {
	_mock.Called(ctx, key)
	return
}

// MockEngine_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockEngine_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockEngine_Expecter) Del(ctx interface{}, key interface{}) *MockEngine_Del_Call {
	return &MockEngine_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockEngine_Del_Call) Run(run func(ctx context.Context, key string)) *MockEngine_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Del_Call) Return() *MockEngine_Del_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEngine_Del_Call) RunAndReturn(run func(ctx context.Context, key string)) *MockEngine_Del_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockEngine
func (_mock *MockEngine) Get(ctx context.Context, key string) (string, bool) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockEngine_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEngine_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockEngine_Expecter) Get(ctx interface{}, key interface{}) *MockEngine_Get_Call {
	return &MockEngine_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockEngine_Get_Call) Run(run func(ctx context.Context, key string)) *MockEngine_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEngine_Get_Call) Return(s string, b bool) *MockEngine_Get_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockEngine_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, bool)) *MockEngine_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockEngine
func (_mock *MockEngine) Set(ctx context.Context, key string, value string) {
	_mock.Called(ctx, key, value)
	return
}

// MockEngine_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockEngine_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *MockEngine_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockEngine_Set_Call {
	return &MockEngine_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockEngine_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockEngine_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEngine_Set_Call) Return() *MockEngine_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEngine_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string)) *MockEngine_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockWAL creates a new instance of MockWAL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWAL(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWAL {
	mock := &MockWAL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWAL is an autogenerated mock type for the WAL type
type MockWAL struct {
	mock.Mock
}

type MockWAL_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWAL) EXPECT() *MockWAL_Expecter {
	return &MockWAL_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockWAL
func (_mock *MockWAL) Del(ctx context.Context, key string) conc.FutureError {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 conc.FutureError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) conc.FutureError); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(conc.FutureError)
	}
	return r0
}

// MockWAL_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockWAL_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx
//   - key
func (_e *MockWAL_Expecter) Del(ctx interface{}, key interface{}) *MockWAL_Del_Call {
	return &MockWAL_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockWAL_Del_Call) Run(run func(ctx context.Context, key string)) *MockWAL_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWAL_Del_Call) Return(v conc.FutureError) *MockWAL_Del_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockWAL_Del_Call) RunAndReturn(run func(ctx context.Context, key string) conc.FutureError) *MockWAL_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Recover provides a mock function for the type MockWAL
func (_mock *MockWAL) Recover() ([]database.WALRecord, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recover")
	}

	var r0 []database.WALRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.WALRecord, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.WALRecord); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.WALRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWAL_Recover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recover'
type MockWAL_Recover_Call struct {
	*mock.Call
}

// Recover is a helper method to define mock.On call
func (_e *MockWAL_Expecter) Recover() *MockWAL_Recover_Call {
	return &MockWAL_Recover_Call{Call: _e.mock.On("Recover")}
}

func (_c *MockWAL_Recover_Call) Run(run func()) *MockWAL_Recover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWAL_Recover_Call) Return(wALRecords []database.WALRecord, err error) *MockWAL_Recover_Call {
	_c.Call.Return(wALRecords, err)
	return _c
}

func (_c *MockWAL_Recover_Call) RunAndReturn(run func() ([]database.WALRecord, error)) *MockWAL_Recover_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockWAL
func (_mock *MockWAL) Set(ctx context.Context, key string, value string) conc.FutureError {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 conc.FutureError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) conc.FutureError); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Get(0).(conc.FutureError)
	}
	return r0
}

// MockWAL_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockWAL_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx
//   - key
//   - value
func (_e *MockWAL_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockWAL_Set_Call {
	return &MockWAL_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockWAL_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockWAL_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWAL_Set_Call) Return(v conc.FutureError) *MockWAL_Set_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockWAL_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) conc.FutureError) *MockWAL_Set_Call {
	_c.Call.Return(run)
	return _c
}
